spring:
  application:
    name: SikaSoftware
  datasource:
    url: 'jdbc:mysql://localhost:3306/sika?serverTimezone=GMT'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static



logging:
  level:
    root: warn
    com:
      zhx: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml